micronaut:
    application:
        name: micronaut-todo
    server:
        port: 6500
router:
    static:
        resources:
            enabled: true
            mapping: /static/**
            paths: classpath:/public
dataSource:
    pooled: true
    dbCreate: create-drop
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password:
jpa:
    default:
        packages-to-scan:
            - 'todo.model'
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
                show_sql: true